{"name": "Logout", "status": "failed", "statusDetails": {"message": "AssertionError: Failure reason: No reason specified\nassert False", "trace": "tests/trajector/test_manual.py:122: in single_test\n    raise e\ntests/trajector/test_manual.py:115: in single_test\n    step()\ntests/trajector/test_manual.py:107: in step_for_test\n    assert answer, f\"Failure reason: {reason_of_failure}\"\nE   AssertionError: Failure reason: No reason specified\nE   assert False"}, "description": "Logout from trajector user portal\n", "steps": [{"name": "Open a trajector user portal", "status": "passed", "start": 1685630723970, "stop": 1685630725273}, {"name": "Sign in using existing user credentials with a valid password", "status": "passed", "start": 1685630725273, "stop": 1685630725956}, {"name": "After login, you are redirected to a portal dashboard", "status": "passed", "start": 1685630725957, "stop": 1685630727419}, {"name": "Logout from trajector user portal", "status": "failed", "statusDetails": {"message": "AssertionError: Failure reason: No reason specified\nassert False\n", "trace": "  File \"/Users/maq/git/trajector-cloud-tests/.venv/lib/python3.9/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/maq/git/trajector-cloud-tests/tests/trajector/test_manual.py\", line 107, in step_for_test\n    assert answer, f\"Failure reason: {reason_of_failure}\"\n"}, "start": 1685630727419, "stop": 1685630733793}], "start": 1685630723970, "stop": 1685630734734, "uuid": "2e2753f3-49c5-455f-8fa1-592bf06693cf", "historyId": "16ec58b37ef0e1740fbd6e31f5fa4aed", "testCaseId": "60141100ff028043c09d00474a6e0e13", "fullName": "tests.trajector.test_manual.TestLogout#test_logout", "labels": [{"name": "severity", "value": "MINOR"}, {"name": "suite", "value": "User portal login"}, {"name": "feature", "value": "Logout"}, {"name": "tag", "value": "logout"}, {"name": "tag", "value": "manual"}, {"name": "parentSuite", "value": "tests.trajector"}, {"name": "subSuite", "value": "TestLogout"}, {"name": "host", "value": "trajector.local"}, {"name": "thread", "value": "80753-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.trajector.test_manual"}]}